#include <iostream>
#include <exception>
using namespace std;


class Overspeed: public exception{
    int speed;
    public:
 const char* what(){
     return "Check out your car speed";
 }
 void getspeed(){
     cout<<"Your car speed is"<<speed <<endl;
 }
 void setspeed(int speed){
     this->speed =speed;
 }
};
class Car{
    
    
    int speed ;
    public:
    Car(){
        speed =0;
        cout<<"speed is zero"<<endl;
    }

void accelerate(){
    for(;;){
        speed +=10;
        cout<<"speed is"<<speed<<endl;
        
if (speed >=250)  {
    Overspeed s;
    s.setspeed(speed);
    throw s;
}  
    
}
}};
    

int main()
{
    Car anilscar;
    try{
        anilscar.accelerate();
    }catch (Overspeed s){
        cout<<s.what()<<endl;  
        s.getspeed();
    }
    return 0;
}
